
// Homepage
const HOMEPAGE_DUMMY_DATA_FETCH_REQUEST = 'HOMEPAGE:DUMMY_DATA:FETCH:REQUEST';
const HOMEPAGE_DUMMY_DATA_FETCH_SUCCESS = 'HOMEPAGE:DUMMY_DATA:FETCH:SUCCESS';
const HOMEPAGE_DUMMY_DATA_FETCH_FAIL = 'HOMEPAGE:DUMMY_DATA:FETCH:FAIL';

export {
  HOMEPAGE_DUMMY_DATA_FETCH_REQUEST,
  HOMEPAGE_DUMMY_DATA_FETCH_SUCCESS,
  HOMEPAGE_DUMMY_DATA_FETCH_FAIL
};
